import mongoose from 'mongoose';

export const QaSummarySchema = new mongoose.Schema({
  domain: { type: String, required: true, index: true },
  jobId: { type: String, index: true },
  scanDate: { type: Date, default: Date.now, index: -1 },
  totalPagesScanned: { type: Number, default: 0 },
  totalBrokenLinks: { type: Number, default: 0 },
  uniqueBrokenLinks: { type: Number, default: 0 },
  brokenLinkStatusCodes: { type: mongoose.Schema.Types.Mixed, default: {} },
  internalBrokenLinks: { type: Number, default: 0 },
  externalBrokenLinks: { type: Number, default: 0 },
  brokenLinksAffectingMostContent: { type: String },
  brokenLinksInSitemap: { type: Number, default: 0 },
  brokenLinksFixed: { type: Number, default: 0 },
  brokenLinksIgnored: { type: Number, default: 0 },
  totalBrokenImages: { type: Number, default: 0 },
  uniqueBrokenImages: { type: Number, default: 0 },
  brokenImagesAffectingMostContent: { type: String },
  pagesWithMisspellings: { type: Number, default: 0 },
  uniqueMisspellings: { type: Number, default: 0 },
  totalMisspellings: { type: Number, default: 0 },
  uniquePotentialMisspellings: { type: Number, default: 0 },
  totalPotentialMisspellings: { type: Number, default: 0 },
  pagesWithPotentialMisspellings: { type: Number, default: 0 },
  pagesWithBrokenLinks: { type: Number, default: 0 },
  pagesWithBrokenImages: { type: Number, default: 0 },
  pagesWithQaErrors: { type: Number, default: 0 },
  contentWithQaErrors: { type: Number, default: 0 },
  misspellingAffectingMostContent: { type: String },
  mostCommonReadabilityLevel: { type: String },
  readabilityDistribution: { type: mongoose.Schema.Types.Mixed, default: {} },
  readabilityPagesCount: { type: Number, default: 0 },
  qaCompliancePercent: { type: Number, default: 100 },
  totalQaIssues: { type: Number, default: 0 },
  topMisspellings: [{ word: String, pagesCount: Number }],
  topPotentialMisspellings: [{ word: String, pagesCount: Number }],
}, { timestamps: true, collection: 'qa_summaries', strict: false });

export const QaSummary = mongoose.model('QaSummary', QaSummarySchema, 'qa_summaries');
